version: "3"

services:
  symfony:
    build: .
    image: moriorgames/symfony-5-php-fpm
    restart: unless-stopped
    env_file:
      - .env
    container_name: symfony-5-php-fpm
    ports:
      - "9000:9000"
    volumes:
      # Comment next line to work locally sync files between your host and docker container
      - "./:/app:cached"
    tty: true

  nginx:
    image: nginx
    container_name: symfony_nginx
    ports:
      - "8090:80"
    volumes:
      - "./:/app:cached"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - symfony
